<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <NoWin32Manifest>true</NoWin32Manifest>
    <ApplicationIcon>WPFPerspectiveEffect.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\Comfortaa.ttf" />
    <None Remove="Shaders\Perspective.ps" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="WPFPerspectiveEffect.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\Comfortaa.ttf" />
    <Resource Include="Shaders\Perspective.ps" />
  </ItemGroup>

</Project>
